Add BottomNavigation component
lugenx/ecohabit pull request #132
Opened 2023-01-25 13:24 UTC by dignit28

### This PR closes the following issue:

- [Issue #129](https://github.com/lugenx/ecohabit/issues/129)

### Changes made:

**1. Regarding the issue**

  - Added `BottomNavigation` folder inside `client/src/components`
  - Added `BottomNavigation.js` file inside `client/src/components/BottomNavigation`
  - Replicated "Bottom navigation with no label" demo from MUI docs
  - Organized imports

**2. Additional changes**

  - Renamed `LabelBottomNavigation()` component to `BottomNavigation()`
    > The task was to copy the demo _**as is**_. I decided to rename the component name from demo to match the file and the folder names to keep naming consistent in the project.

2023-01-26 02:06 UTC, rcamach7 requested changes
Nice call on updating the component name! Just the small import change and we can merge this in!

2023-01-26 02:06 UTC, rcamach7 commented on client/src/components/BottomNavigation/BottomNavigation.js
> +import FolderIcon from "@mui/icons-material/Folder";
Could you group all the icons into a single import, to follow the same pattern in other components? MUI uses a custom name from the actual import location, like below, so just import using the `as` keyboard to keep the custom names MUI used

import { Folder as FolderIcon, etc } from "@mui/icons-material/";

2023-01-26 22:41 UTC, dignit28 commented
1. I have made the changes to imports as was asked in requested changes.

2. I also undid the name change to the component as it was giving me this error:
`Parsing error: Identifier 'BottomNavigation' has already been declared.`
I didn't see it when I first changed it.

3. I still think that name of the component's file and name of the component itself should be the same.
   Since `BottomNavigation` is already taken by the MUI component, I decided to name our new component `BottomNavigationBar` for now, and named its file and directory accordingly.

2023-01-29 22:49 UTC, rcamach7 commented
> 1. I have made the changes to imports as was requested.
> 2. I also undid the name change to the component as it was giving me this error:
>    `Parsing error: Identifier 'BottomNavigation' has already been declared.`
>    I didn't see it when I first changed it.
> 3. I still think that name of the component's file and name of the component itself should be the same.
>    Since `BottomNavigation` is already taken by the MUI component, I decided to name our new component `BottomNavigationBar` for now, and named its file and directory accordingly.

I agree, both component name and file should be the same, thank you for updating that! We are good to merge this in 👍

2023-01-29 22:49 UTC, rcamach7 approved these changes

2023-01-30 01:58 UTC, lugenx approved these changes
thank you @dignit28 👍

2023-01-30 01:58 UTC, merged