Added links to tech stack
lugenx/ecohabit pull request #176
Opened 2023-03-17 05:16 UTC by the-amazing-atharva

+ Added links to tech stack
+ Added target="_blank" attribute so that it opens in new tab

Thoughts @lugenx ?

Fixes #173

2023-03-18 02:08 UTC, lugenx requested changes
thank you, this looks good when rendered, but, Is there a way to do it without using HTML? I want to keep it markdown only for now for simplicity.

2023-03-18 12:30 UTC, the-amazing-atharva commented
Will have to research a bit, working on it
Will update here!

2023-03-20 12:25 UTC, the-amazing-atharva commented
Hey!
I converted it to markdown but it seems that we can only open links in the same tab

2023-03-20 12:39 UTC, tsimian commented
> Hey! I converted it to markdown but it seems that we can only open links in the same tab

Yeah, I don't think this is currently possible with plain markdown. Perhaps we could still use an anchor tag, but only for each tech like so...
```
## Tech Stack

- Front End: <a href="https://reactjs.org/" target="_blank">React (JavaScript)</a>, <a href="https://mui.com/" target="_blank">Material UI</a>
```

What are your thoughts @lugenx?

2023-03-20 18:12 UTC, tsimian commented
> @the-amazing-atharva thank you, i just have one comment about replacing the MongoDB link. @tsimian, i still think we should go with markdown only, do you think opening on the same page is an issue? wouldn't most people click with the cmd/ctrl for this kind of link anyway? 🤔

Yeah, I agree. There are other methods to open in a new tab. Though I felt it was worth mentioning that plain markdown does not support the target attribute. Linking to the documentation is a good idea though.

2023-03-21 10:20 UTC, the-amazing-atharva commented
Thanks @tsimian and @lugenx 
Do I have to change anything?? 
Something regarding the MongoDB link was mentioned above ig

2023-03-21 12:39 UTC, lugenx requested changes
sorry looks like my comment related to mongo db stayed pending, I haven't posted it, you should see it now.

2023-03-29 04:16 UTC, lugenx commented on README.md
> +*   **Database:** [MongoDB](https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwjbkKiXmOL9AhUGmWYCHTVNBA0YABAAGgJzbQ&ohost=www.google.com&cid=CAASJuRoPXQHwswO-Z51bFJxJzJQgk5pfhUHekUpyg4nhr0O1
@the-amazing-atharva, any update on this?

2023-03-29 05:55 UTC, the-amazing-atharva commented on README.md
> +*   **Database:** [MongoDB](https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwjbkKiXmOL9AhUGmWYCHTVNBA0YABAAGgJzbQ&ohost=www.google.com&cid=CAASJuRoPXQHwswO-Z51bFJxJzJQgk5pfhUHekUpyg4nhr0O1
On it brother!! @lugenx

2023-03-29 05:56 UTC, the-amazing-atharva commented
Updated the MongDB section
Any more changes @lugenx ?

2023-03-31 05:51 UTC, lugenx commented
looks good @the-amazing-atharva , thank you 👍

2023-03-31 05:52 UTC, lugenx approved these changes

2023-03-31 05:52 UTC, merged

2023-03-31 05:53 UTC, the-amazing-atharva commented
> looks good @the-amazing-atharva , thank you 👍

It was a pleasure working with you @lugenx 😄