Implement authentication functionality
lugenx/ecohabit pull request #180
Opened 2023-03-20 21:01 UTC by lugenx

this pull request implements the authentication functionality for the application by communicating with the back-end with already created endpoints. the following changes have been made:

- corrected the naming of some variables for consistency
- implemented registration, login, and logout functionality
- added and used Context API for state management.
- added registration success message
- added login failure messages

how to test:

to test the changes, follow these steps:

1. click on the "Sign up" button and fill out the registration form.
2. once you've registered, you should get a success message and be directed to the login page. 
3. try logging in using the credentials you just created.
4. if the login is successful, you should be redirected to the main page. If the login fails, you should see error messages.
5. to log out, click on the "Logout" button.

2023-03-23 13:10 UTC, tsimian commented
I tested it and it looks good to me @lugenx, I just have a couple of comments:
- Upon registering, should we display a message to the UI if the user already exists?
- Also, there is still missing validation on the front end if empty fields on Register (this could maybe be handled in a separate PR)
- Perhaps we check if the user is logged in on certain pages like 'Home' or 'Profile', and navigate to `/login` if `loggedIn` is set to false in `LoginContext`.

2023-03-25 08:04 UTC, lugenx commented
thank you, @tsimian, i addressed your first and third comments. i think we will need to create an additional issue for validations.

2023-03-25 14:15 UTC, tsimian approved these changes
This is a big milestone for the project, great job @lugenx!

2023-04-05 02:06 UTC, rcamach7 requested changes
Overall looks great! The error handling is on point.

2023-04-05 02:06 UTC, rcamach7 commented on client/src/pages/ProfilePage.js
This might be out of scope for this PR but what do you think about adding an additional context, UserContext? It would handle two things (react states):
- User data (name, habits, email, and any other info)
- token (will store token if user is logged in)

Any components that need any type of user data would be pulling it all from here. This context can also handle requesting user information anytime it detects a token as been added (using a useEffect). We can move this to another ticket / issue if needed, but I'd like to get your thoughts

2023-04-15 04:46 UTC, lugenx reviewed
@rcamach7 i made updates according to your comments. thank you.

2023-04-15 04:46 UTC, lugenx commented on client/src/contexts/LoginContext.js
> +
this is done, could you please review it

2023-04-15 04:46 UTC, lugenx commented on client/src/contexts/RegisterContext.js
this is done, could you please review it

2023-04-15 04:46 UTC, lugenx commented on client/src/pages/ProfilePage.js
yes, that's a good idea. let's create a different issue just for this.

2023-04-15 04:48 UTC, lugenx commented on client/src/components/Login/Register.js
>    const [accept, setAccept] = useState(false);
this is done, could you please review it

2023-04-17 20:21 UTC, rcamach7 approved these changes
Looks great!

2023-04-18 00:21 UTC, merged