Email and password validation #185
lugenx/ecohabit pull request #187
Opened 2023-04-26 12:02 UTC by vishwaszadte

## PR Summary

#### ADDED
- Added `validator` as a dependency

#### CHANGED
- Changed `userLogin` controller to validate email
- Changed `userSignup` controller to validate email as well as password

## How to test 
1. In Postman, create a Post request on the following URLs -> `http://localhost:3001/user/signup` (for email, password) and `http://localhost:3001/user/login` (for email) 
2. Try invalid email and/or weak password (not containing 8 chars or without a number or special character) in the request body

2023-04-26 22:44 UTC, lugenx requested changes
thank you, @vishwaszadte, this looks great. I just have one comment about changing the error message. I will wait for @tsimian also review this before the merge.

2023-04-27 12:57 UTC, tsimian approved these changes
Looks good to me @lugenx. Nice work @vishwaszadte!

2023-04-27 15:10 UTC, vishwaszadte commented on server/src/controller/userController.js
> +        "Password not strong enough. A strong password is minimum 8 characters long containing at least 1 number and 1 special character.",
@lugenx I've made the requested change

2023-04-27 15:11 UTC, vishwaszadte commented
>

2023-04-27 19:15 UTC, lugenx approved these changes
Great work @vishwaszadte, thank you so much 👍

2023-04-27 19:16 UTC, merged